/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7f6ee30e-00ce-41fa-b079-865bfe7f11f8",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yFoNV1m4r",
    "aws_user_pools_web_client_id": "5r6d7vgfjrj1cbks8qbve117np",
    "oauth": {}
};


export default awsmobile;
